### ISSUE TITLE
회원가입 View 구현

### ISSUE THREAD

**Issue by aaronforge** [pers0n4/dnd-mentee-3rd-1-repo#15]
- 필요한 요소
  - Email
    - [x] ios
    - [x] android
  - 닉네임
    - [x] ios
    - [x] android
  - 비밀번호
    - [x] ios
    - [x] android
  - 비밀번호 확인
    - [x] ios
    - [x] android
  - 확인 버튼
    - [x] ios
    - [x] android

- 필요한 기능
  - 이메일 중복검사
    - 중복 시 Alert 생성 후 return
      - [x] ios
      - [x] android
  - 비밀번호 확인
    - 비밀번호와 비밀번호 확인 값 일치 여부
      - [x] ios
      - [x] android
  - 확인 버튼 액션
    - 정보 저장 
      - [x] ios
      - [x] android
  - 뒤로 가기 버튼
    - 이전 뷰 호출
      - [x] ios
      - [x] android

**Comment by aaronLab** [comment]
취소 버튼 => Back Button in the Navigation Bar
